# This script deploys your website automatically
name: CI

# Only trigger this script when you push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      # run npm test, build, lint, etc.
      
      - name: Install required Packages
        run: npm install
        
      - name: Setting User
        run:  git config --global user.name "saiviswateja"
      
      - name: Authenticating User
        run: git config --global user.email "saiviswateja.teja@gmail.com"
        
       # Run our deployment command
      - name: Deploying the static website to gh-pages
        run: npm run deploy
        env:
          CI: ""
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
